server:
  port: 8888

spring:
  datasource:
    # \u914D\u7F6E\u6570\u636E\u6E90
    driver-class-name: com.mysql.jdbc.Driver
    # \u4F7F\u7528druid\u8FDE\u63A5\u6C60
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/pro?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: root

###\u589E\u52A0\u65E5\u5FD7\u8F93\u51FA\uFF0C\u65B9\u4FBF\u5B9A\u4F4D\u95EE\u9898
logging:
  level:
    root : warn
    com.cxyxs.mybatisplus.dao: trace
  ###\u63A7\u5236\u53F0\u8F93\u51FA\u683C\u5F0F
  pattern:
    console: '%p%m%n'

mybatis-plus:
  mapper-locations: classpath*:/com/dsy/mapper/xml/*.xml
  global-config:
    db-config:
      ###\u903B\u8F91\u672A\u5220\u9664\u7684\u503C
      logic-not-delete-value: 0
      ###\u903B\u8F91\u5DF2\u5220\u9664\u7684\u503C
      logic-delete-value: 1


  ####\u626B\u63CFswagger\u6CE8\u89E3
  swagger:
    base-package: com.dsy