spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_jpa?serverTimezone=GMT%2B8
    username: root
    password: root

  Jpa:
    hibernate:
      # \u66F4\u65B0\u6216\u521B\u5EFA\u6570\u636E\u8868
      ddl-auto: update
    # \u5728\u63A7\u5236\u53F0\u663E\u793Asql
    show-sql: true
